name: Test on any push

on:
  push:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.8'


    - name: Run tests with pytest
      env:
        PYTHONPATH: ${{ github.workspace }}
      
      run: |
        cd tests/
        pip install pytest
        pytest        
